services:
  - type: web
    name: book-exchange-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://book-exchange-api.onrender.com 