services:
  - type: web
    name: book-exchange
    env: node
    buildCommand: |
      npm run build
      echo "Build complete. Checking client/dist directory:"
      ls -la client/dist/
      echo "Detailed contents of client/dist directory:"
      find client/dist -type f || echo "No files found in client/dist"
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_API_KEY
        sync: false
      - key: TWILIO_API_SECRET
        sync: false 