services:
  - type: web
    name: book-exchange
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
      rm -rf dist
      mkdir -p dist
      cp -r client/dist/* dist/
      ls -la dist/
      echo "Contents of dist directory:"
      find dist -type f
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_API_KEY
        sync: false
      - key: TWILIO_API_SECRET
        sync: false 